export const SET_FILTER_MODAL_DAYS = 'SET_FILTER_MODAL_DAYS';
export const SET_BUSINESS_WITH_FIELDS = 'SET_BUSINESS_WITH_FIELDS';
export const SET_FIELDS_BY_BUSINESS = 'SET_FIELDS_BY_BUSINESS';
export const SET_MY_RESERVATIONS = 'SET_MY_RESERVATIONS';
export const SET_BUSINESS_INFO = 'SET_BUSINESS_INFO';
export const CLEAR_BUSINESS_INFO_AND_COURTS = 'CLEAR_BUSINESS_INFO_AND_COURTS';
